workflows:
  ios-build:
    name: ParkFinder iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      xcode: latest
      vars:
        XCODE_SCHEME: ParkingApp
        XCODE_PROJECT: ParkingApp.xcodeproj

    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          xcodegen generate
          echo "✅ Xcode project generated"

      - name: Set build version
        script: |
          BUILD_NUMBER=$PROJECT_BUILD_NUMBER
          agvtool new-version -all $BUILD_NUMBER

      - name: Build (no code signing)
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS Simulator" \
            -derivedDataPath build/DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty --utf --color

    artifacts:
      - build/DerivedData/Build/Products/**/*.app

    publishing:
      slack:
        channel: "#builds"
        notify_on_build_start: false
        notify:
          success: true
          failure: true
